//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("schooldbModel", "student_ibfk_1", "classes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(School_Management_System.Models.@class), "student", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(School_Management_System.Models.student), true)]
[assembly: EdmRelationshipAttribute("schooldbModel", "fees_ibfk_1", "student", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(School_Management_System.Models.student), "fees", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(School_Management_System.Models.fee), true)]
[assembly: EdmRelationshipAttribute("schooldbModel", "sections_ibfk_1", "class", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(School_Management_System.Models.@class), "section", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(School_Management_System.Models.section), true)]

#endregion

namespace School_Management_System.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class schooldbEntities10 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new schooldbEntities10 object using the connection string found in the 'schooldbEntities10' section of the application configuration file.
        /// </summary>
        public schooldbEntities10() : base("name=schooldbEntities10", "schooldbEntities10")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new schooldbEntities10 object.
        /// </summary>
        public schooldbEntities10(string connectionString) : base(connectionString, "schooldbEntities10")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new schooldbEntities10 object.
        /// </summary>
        public schooldbEntities10(EntityConnection connection) : base(connection, "schooldbEntities10")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<attendance> attendances
        {
            get
            {
                if ((_attendances == null))
                {
                    _attendances = base.CreateObjectSet<attendance>("attendances");
                }
                return _attendances;
            }
        }
        private ObjectSet<attendance> _attendances;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<@class> classes
        {
            get
            {
                if ((_classes == null))
                {
                    _classes = base.CreateObjectSet<@class>("classes");
                }
                return _classes;
            }
        }
        private ObjectSet<@class> _classes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<family> families
        {
            get
            {
                if ((_families == null))
                {
                    _families = base.CreateObjectSet<family>("families");
                }
                return _families;
            }
        }
        private ObjectSet<family> _families;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<fee> fees
        {
            get
            {
                if ((_fees == null))
                {
                    _fees = base.CreateObjectSet<fee>("fees");
                }
                return _fees;
            }
        }
        private ObjectSet<fee> _fees;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<student> students
        {
            get
            {
                if ((_students == null))
                {
                    _students = base.CreateObjectSet<student>("students");
                }
                return _students;
            }
        }
        private ObjectSet<student> _students;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<teacher> teachers
        {
            get
            {
                if ((_teachers == null))
                {
                    _teachers = base.CreateObjectSet<teacher>("teachers");
                }
                return _teachers;
            }
        }
        private ObjectSet<teacher> _teachers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<section> sections
        {
            get
            {
                if ((_sections == null))
                {
                    _sections = base.CreateObjectSet<section>("sections");
                }
                return _sections;
            }
        }
        private ObjectSet<section> _sections;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<timing> timings
        {
            get
            {
                if ((_timings == null))
                {
                    _timings = base.CreateObjectSet<timing>("timings");
                }
                return _timings;
            }
        }
        private ObjectSet<timing> _timings;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the attendances EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToattendances(attendance attendance)
        {
            base.AddObject("attendances", attendance);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the classes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToclasses(@class @class)
        {
            base.AddObject("classes", @class);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the families EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTofamilies(family family)
        {
            base.AddObject("families", family);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the fees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTofees(fee fee)
        {
            base.AddObject("fees", fee);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the students EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTostudents(student student)
        {
            base.AddObject("students", student);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the teachers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToteachers(teacher teacher)
        {
            base.AddObject("teachers", teacher);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sections EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosections(section section)
        {
            base.AddObject("sections", section);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the timings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotimings(timing timing)
        {
            base.AddObject("timings", timing);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="schooldbModel", Name="attendance")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class attendance : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new attendance object.
        /// </summary>
        /// <param name="attendanceDate">Initial value of the AttendanceDate property.</param>
        /// <param name="teacherId">Initial value of the teacherId property.</param>
        public static attendance Createattendance(global::System.DateTime attendanceDate, global::System.Int32 teacherId)
        {
            attendance attendance = new attendance();
            attendance.AttendanceDate = attendanceDate;
            attendance.teacherId = teacherId;
            return attendance;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> attendanceId
        {
            get
            {
                return _attendanceId;
            }
            set
            {
                OnattendanceIdChanging(value);
                ReportPropertyChanging("attendanceId");
                _attendanceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("attendanceId");
                OnattendanceIdChanged();
            }
        }
        private Nullable<global::System.Int32> _attendanceId;
        partial void OnattendanceIdChanging(Nullable<global::System.Int32> value);
        partial void OnattendanceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AttendanceDate
        {
            get
            {
                return _AttendanceDate;
            }
            set
            {
                if (_AttendanceDate != value)
                {
                    OnAttendanceDateChanging(value);
                    ReportPropertyChanging("AttendanceDate");
                    _AttendanceDate = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AttendanceDate");
                    OnAttendanceDateChanged();
                }
            }
        }
        private global::System.DateTime _AttendanceDate;
        partial void OnAttendanceDateChanging(global::System.DateTime value);
        partial void OnAttendanceDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 teacherId
        {
            get
            {
                return _teacherId;
            }
            set
            {
                if (_teacherId != value)
                {
                    OnteacherIdChanging(value);
                    ReportPropertyChanging("teacherId");
                    _teacherId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("teacherId");
                    OnteacherIdChanged();
                }
            }
        }
        private global::System.Int32 _teacherId;
        partial void OnteacherIdChanging(global::System.Int32 value);
        partial void OnteacherIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IsPresent
        {
            get
            {
                return _IsPresent;
            }
            set
            {
                OnIsPresentChanging(value);
                ReportPropertyChanging("IsPresent");
                _IsPresent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IsPresent");
                OnIsPresentChanged();
            }
        }
        private global::System.String _IsPresent;
        partial void OnIsPresentChanging(global::System.String value);
        partial void OnIsPresentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> SalaryDeduction
        {
            get
            {
                return _SalaryDeduction;
            }
            set
            {
                OnSalaryDeductionChanging(value);
                ReportPropertyChanging("SalaryDeduction");
                _SalaryDeduction = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SalaryDeduction");
                OnSalaryDeductionChanged();
            }
        }
        private Nullable<global::System.Double> _SalaryDeduction;
        partial void OnSalaryDeductionChanging(Nullable<global::System.Double> value);
        partial void OnSalaryDeductionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> AttendanceExitDate
        {
            get
            {
                return _AttendanceExitDate;
            }
            set
            {
                OnAttendanceExitDateChanging(value);
                ReportPropertyChanging("AttendanceExitDate");
                _AttendanceExitDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AttendanceExitDate");
                OnAttendanceExitDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _AttendanceExitDate;
        partial void OnAttendanceExitDateChanging(Nullable<global::System.DateTime> value);
        partial void OnAttendanceExitDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="schooldbModel", Name="class")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class @class : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new class object.
        /// </summary>
        /// <param name="classId">Initial value of the classId property.</param>
        public static @class Createclass(global::System.Int32 classId)
        {
            @class @class = new @class();
            @class.classId = classId;
            return @class;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 classId
        {
            get
            {
                return _classId;
            }
            set
            {
                if (_classId != value)
                {
                    OnclassIdChanging(value);
                    ReportPropertyChanging("classId");
                    _classId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("classId");
                    OnclassIdChanged();
                }
            }
        }
        private global::System.Int32 _classId;
        partial void OnclassIdChanging(global::System.Int32 value);
        partial void OnclassIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String className
        {
            get
            {
                return _className;
            }
            set
            {
                OnclassNameChanging(value);
                ReportPropertyChanging("className");
                _className = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("className");
                OnclassNameChanged();
            }
        }
        private global::System.String _className;
        partial void OnclassNameChanging(global::System.String value);
        partial void OnclassNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> classFee
        {
            get
            {
                return _classFee;
            }
            set
            {
                OnclassFeeChanging(value);
                ReportPropertyChanging("classFee");
                _classFee = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("classFee");
                OnclassFeeChanged();
            }
        }
        private Nullable<global::System.Int32> _classFee;
        partial void OnclassFeeChanging(Nullable<global::System.Int32> value);
        partial void OnclassFeeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schooldbModel", "student_ibfk_1", "student")]
        public EntityCollection<student> students
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<student>("schooldbModel.student_ibfk_1", "student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<student>("schooldbModel.student_ibfk_1", "student", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schooldbModel", "sections_ibfk_1", "section")]
        public EntityCollection<section> sections
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<section>("schooldbModel.sections_ibfk_1", "section");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<section>("schooldbModel.sections_ibfk_1", "section", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="schooldbModel", Name="family")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class family : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new family object.
        /// </summary>
        /// <param name="familyId">Initial value of the familyId property.</param>
        public static family Createfamily(global::System.Int32 familyId)
        {
            family family = new family();
            family.familyId = familyId;
            return family;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 familyId
        {
            get
            {
                return _familyId;
            }
            set
            {
                if (_familyId != value)
                {
                    OnfamilyIdChanging(value);
                    ReportPropertyChanging("familyId");
                    _familyId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("familyId");
                    OnfamilyIdChanged();
                }
            }
        }
        private global::System.Int32 _familyId;
        partial void OnfamilyIdChanging(global::System.Int32 value);
        partial void OnfamilyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FatherName
        {
            get
            {
                return _FatherName;
            }
            set
            {
                OnFatherNameChanging(value);
                ReportPropertyChanging("FatherName");
                _FatherName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FatherName");
                OnFatherNameChanged();
            }
        }
        private global::System.String _FatherName;
        partial void OnFatherNameChanging(global::System.String value);
        partial void OnFatherNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FatherNIC
        {
            get
            {
                return _FatherNIC;
            }
            set
            {
                OnFatherNICChanging(value);
                ReportPropertyChanging("FatherNIC");
                _FatherNIC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FatherNIC");
                OnFatherNICChanged();
            }
        }
        private global::System.String _FatherNIC;
        partial void OnFatherNICChanging(global::System.String value);
        partial void OnFatherNICChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FatherEducation
        {
            get
            {
                return _FatherEducation;
            }
            set
            {
                OnFatherEducationChanging(value);
                ReportPropertyChanging("FatherEducation");
                _FatherEducation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FatherEducation");
                OnFatherEducationChanged();
            }
        }
        private global::System.String _FatherEducation;
        partial void OnFatherEducationChanging(global::System.String value);
        partial void OnFatherEducationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FatherIncome
        {
            get
            {
                return _FatherIncome;
            }
            set
            {
                OnFatherIncomeChanging(value);
                ReportPropertyChanging("FatherIncome");
                _FatherIncome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FatherIncome");
                OnFatherIncomeChanged();
            }
        }
        private global::System.String _FatherIncome;
        partial void OnFatherIncomeChanging(global::System.String value);
        partial void OnFatherIncomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FatherOccupation
        {
            get
            {
                return _FatherOccupation;
            }
            set
            {
                OnFatherOccupationChanging(value);
                ReportPropertyChanging("FatherOccupation");
                _FatherOccupation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FatherOccupation");
                OnFatherOccupationChanged();
            }
        }
        private global::System.String _FatherOccupation;
        partial void OnFatherOccupationChanging(global::System.String value);
        partial void OnFatherOccupationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MotherName
        {
            get
            {
                return _MotherName;
            }
            set
            {
                OnMotherNameChanging(value);
                ReportPropertyChanging("MotherName");
                _MotherName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MotherName");
                OnMotherNameChanged();
            }
        }
        private global::System.String _MotherName;
        partial void OnMotherNameChanging(global::System.String value);
        partial void OnMotherNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MotherNIC
        {
            get
            {
                return _MotherNIC;
            }
            set
            {
                OnMotherNICChanging(value);
                ReportPropertyChanging("MotherNIC");
                _MotherNIC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MotherNIC");
                OnMotherNICChanged();
            }
        }
        private global::System.String _MotherNIC;
        partial void OnMotherNICChanging(global::System.String value);
        partial void OnMotherNICChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MotherEducation
        {
            get
            {
                return _MotherEducation;
            }
            set
            {
                OnMotherEducationChanging(value);
                ReportPropertyChanging("MotherEducation");
                _MotherEducation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MotherEducation");
                OnMotherEducationChanged();
            }
        }
        private global::System.String _MotherEducation;
        partial void OnMotherEducationChanging(global::System.String value);
        partial void OnMotherEducationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MotherIncome
        {
            get
            {
                return _MotherIncome;
            }
            set
            {
                OnMotherIncomeChanging(value);
                ReportPropertyChanging("MotherIncome");
                _MotherIncome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MotherIncome");
                OnMotherIncomeChanged();
            }
        }
        private global::System.String _MotherIncome;
        partial void OnMotherIncomeChanging(global::System.String value);
        partial void OnMotherIncomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MotherOccupation
        {
            get
            {
                return _MotherOccupation;
            }
            set
            {
                OnMotherOccupationChanging(value);
                ReportPropertyChanging("MotherOccupation");
                _MotherOccupation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MotherOccupation");
                OnMotherOccupationChanged();
            }
        }
        private global::System.String _MotherOccupation;
        partial void OnMotherOccupationChanging(global::System.String value);
        partial void OnMotherOccupationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Religion
        {
            get
            {
                return _Religion;
            }
            set
            {
                OnReligionChanging(value);
                ReportPropertyChanging("Religion");
                _Religion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Religion");
                OnReligionChanged();
            }
        }
        private global::System.String _Religion;
        partial void OnReligionChanging(global::System.String value);
        partial void OnReligionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Caste
        {
            get
            {
                return _Caste;
            }
            set
            {
                OnCasteChanging(value);
                ReportPropertyChanging("Caste");
                _Caste = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Caste");
                OnCasteChanged();
            }
        }
        private global::System.String _Caste;
        partial void OnCasteChanging(global::System.String value);
        partial void OnCasteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nationality
        {
            get
            {
                return _Nationality;
            }
            set
            {
                OnNationalityChanging(value);
                ReportPropertyChanging("Nationality");
                _Nationality = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nationality");
                OnNationalityChanged();
            }
        }
        private global::System.String _Nationality;
        partial void OnNationalityChanging(global::System.String value);
        partial void OnNationalityChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="schooldbModel", Name="fee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class fee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new fee object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="month">Initial value of the Month property.</param>
        /// <param name="year">Initial value of the Year property.</param>
        /// <param name="basic_Fee">Initial value of the Basic_Fee property.</param>
        /// <param name="net_Fee">Initial value of the Net_Fee property.</param>
        /// <param name="is_Paid">Initial value of the Is_Paid property.</param>
        /// <param name="studentId">Initial value of the studentId property.</param>
        /// <param name="day">Initial value of the Day property.</param>
        public static fee Createfee(global::System.Int32 id, global::System.String month, global::System.String year, global::System.Single basic_Fee, global::System.Single net_Fee, global::System.Boolean is_Paid, global::System.Int32 studentId, global::System.Int32 day)
        {
            fee fee = new fee();
            fee.Id = id;
            fee.Month = month;
            fee.Year = year;
            fee.Basic_Fee = basic_Fee;
            fee.Net_Fee = net_Fee;
            fee.Is_Paid = is_Paid;
            fee.studentId = studentId;
            fee.Day = day;
            return fee;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Month
        {
            get
            {
                return _Month;
            }
            set
            {
                OnMonthChanging(value);
                ReportPropertyChanging("Month");
                _Month = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Month");
                OnMonthChanged();
            }
        }
        private global::System.String _Month;
        partial void OnMonthChanging(global::System.String value);
        partial void OnMonthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Year
        {
            get
            {
                return _Year;
            }
            set
            {
                OnYearChanging(value);
                ReportPropertyChanging("Year");
                _Year = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Year");
                OnYearChanged();
            }
        }
        private global::System.String _Year;
        partial void OnYearChanging(global::System.String value);
        partial void OnYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single Basic_Fee
        {
            get
            {
                return _Basic_Fee;
            }
            set
            {
                OnBasic_FeeChanging(value);
                ReportPropertyChanging("Basic_Fee");
                _Basic_Fee = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Basic_Fee");
                OnBasic_FeeChanged();
            }
        }
        private global::System.Single _Basic_Fee;
        partial void OnBasic_FeeChanging(global::System.Single value);
        partial void OnBasic_FeeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> Concession
        {
            get
            {
                return _Concession;
            }
            set
            {
                OnConcessionChanging(value);
                ReportPropertyChanging("Concession");
                _Concession = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Concession");
                OnConcessionChanged();
            }
        }
        private Nullable<global::System.Single> _Concession;
        partial void OnConcessionChanging(Nullable<global::System.Single> value);
        partial void OnConcessionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single Net_Fee
        {
            get
            {
                return _Net_Fee;
            }
            set
            {
                OnNet_FeeChanging(value);
                ReportPropertyChanging("Net_Fee");
                _Net_Fee = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Net_Fee");
                OnNet_FeeChanged();
            }
        }
        private global::System.Single _Net_Fee;
        partial void OnNet_FeeChanging(global::System.Single value);
        partial void OnNet_FeeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Is_Paid
        {
            get
            {
                return _Is_Paid;
            }
            set
            {
                OnIs_PaidChanging(value);
                ReportPropertyChanging("Is_Paid");
                _Is_Paid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Is_Paid");
                OnIs_PaidChanged();
            }
        }
        private global::System.Boolean _Is_Paid;
        partial void OnIs_PaidChanging(global::System.Boolean value);
        partial void OnIs_PaidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 studentId
        {
            get
            {
                return _studentId;
            }
            set
            {
                OnstudentIdChanging(value);
                ReportPropertyChanging("studentId");
                _studentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("studentId");
                OnstudentIdChanged();
            }
        }
        private global::System.Int32 _studentId;
        partial void OnstudentIdChanging(global::System.Int32 value);
        partial void OnstudentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Day
        {
            get
            {
                return _Day;
            }
            set
            {
                OnDayChanging(value);
                ReportPropertyChanging("Day");
                _Day = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Day");
                OnDayChanged();
            }
        }
        private global::System.Int32 _Day;
        partial void OnDayChanging(global::System.Int32 value);
        partial void OnDayChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schooldbModel", "fees_ibfk_1", "student")]
        public student student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<student>("schooldbModel.fees_ibfk_1", "student").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<student>("schooldbModel.fees_ibfk_1", "student").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<student> studentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<student>("schooldbModel.fees_ibfk_1", "student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<student>("schooldbModel.fees_ibfk_1", "student", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="schooldbModel", Name="section")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class section : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new section object.
        /// </summary>
        /// <param name="sectionId">Initial value of the sectionId property.</param>
        public static section Createsection(global::System.Int32 sectionId)
        {
            section section = new section();
            section.sectionId = sectionId;
            return section;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sectionId
        {
            get
            {
                return _sectionId;
            }
            set
            {
                if (_sectionId != value)
                {
                    OnsectionIdChanging(value);
                    ReportPropertyChanging("sectionId");
                    _sectionId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("sectionId");
                    OnsectionIdChanged();
                }
            }
        }
        private global::System.Int32 _sectionId;
        partial void OnsectionIdChanging(global::System.Int32 value);
        partial void OnsectionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sectionName
        {
            get
            {
                return _sectionName;
            }
            set
            {
                OnsectionNameChanging(value);
                ReportPropertyChanging("sectionName");
                _sectionName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sectionName");
                OnsectionNameChanged();
            }
        }
        private global::System.String _sectionName;
        partial void OnsectionNameChanging(global::System.String value);
        partial void OnsectionNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> classId
        {
            get
            {
                return _classId;
            }
            set
            {
                OnclassIdChanging(value);
                ReportPropertyChanging("classId");
                _classId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("classId");
                OnclassIdChanged();
            }
        }
        private Nullable<global::System.Int32> _classId;
        partial void OnclassIdChanging(Nullable<global::System.Int32> value);
        partial void OnclassIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schooldbModel", "sections_ibfk_1", "class")]
        public @class @class
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<@class>("schooldbModel.sections_ibfk_1", "class").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<@class>("schooldbModel.sections_ibfk_1", "class").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<@class> classReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<@class>("schooldbModel.sections_ibfk_1", "class");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<@class>("schooldbModel.sections_ibfk_1", "class", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="schooldbModel", Name="student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class student : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new student object.
        /// </summary>
        /// <param name="studentId">Initial value of the studentId property.</param>
        public static student Createstudent(global::System.Int32 studentId)
        {
            student student = new student();
            student.studentId = studentId;
            return student;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 studentId
        {
            get
            {
                return _studentId;
            }
            set
            {
                if (_studentId != value)
                {
                    OnstudentIdChanging(value);
                    ReportPropertyChanging("studentId");
                    _studentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("studentId");
                    OnstudentIdChanged();
                }
            }
        }
        private global::System.Int32 _studentId;
        partial void OnstudentIdChanging(global::System.Int32 value);
        partial void OnstudentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateOfAdmission
        {
            get
            {
                return _DateOfAdmission;
            }
            set
            {
                OnDateOfAdmissionChanging(value);
                ReportPropertyChanging("DateOfAdmission");
                _DateOfAdmission = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfAdmission");
                OnDateOfAdmissionChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateOfAdmission;
        partial void OnDateOfAdmissionChanging(Nullable<global::System.DateTime> value);
        partial void OnDateOfAdmissionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EducationMedium
        {
            get
            {
                return _EducationMedium;
            }
            set
            {
                OnEducationMediumChanging(value);
                ReportPropertyChanging("EducationMedium");
                _EducationMedium = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EducationMedium");
                OnEducationMediumChanged();
            }
        }
        private global::System.String _EducationMedium;
        partial void OnEducationMediumChanging(global::System.String value);
        partial void OnEducationMediumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StudyClass
        {
            get
            {
                return _StudyClass;
            }
            set
            {
                OnStudyClassChanging(value);
                ReportPropertyChanging("StudyClass");
                _StudyClass = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StudyClass");
                OnStudyClassChanged();
            }
        }
        private global::System.String _StudyClass;
        partial void OnStudyClassChanging(global::System.String value);
        partial void OnStudyClassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> classId
        {
            get
            {
                return _classId;
            }
            set
            {
                OnclassIdChanging(value);
                ReportPropertyChanging("classId");
                _classId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("classId");
                OnclassIdChanged();
            }
        }
        private Nullable<global::System.Int32> _classId;
        partial void OnclassIdChanging(Nullable<global::System.Int32> value);
        partial void OnclassIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StudentGender
        {
            get
            {
                return _StudentGender;
            }
            set
            {
                OnStudentGenderChanging(value);
                ReportPropertyChanging("StudentGender");
                _StudentGender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StudentGender");
                OnStudentGenderChanged();
            }
        }
        private global::System.String _StudentGender;
        partial void OnStudentGenderChanging(global::System.String value);
        partial void OnStudentGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StudentName
        {
            get
            {
                return _StudentName;
            }
            set
            {
                OnStudentNameChanging(value);
                ReportPropertyChanging("StudentName");
                _StudentName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StudentName");
                OnStudentNameChanged();
            }
        }
        private global::System.String _StudentName;
        partial void OnStudentNameChanging(global::System.String value);
        partial void OnStudentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StudentDOB
        {
            get
            {
                return _StudentDOB;
            }
            set
            {
                OnStudentDOBChanging(value);
                ReportPropertyChanging("StudentDOB");
                _StudentDOB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StudentDOB");
                OnStudentDOBChanged();
            }
        }
        private Nullable<global::System.DateTime> _StudentDOB;
        partial void OnStudentDOBChanging(Nullable<global::System.DateTime> value);
        partial void OnStudentDOBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StudentAddress
        {
            get
            {
                return _StudentAddress;
            }
            set
            {
                OnStudentAddressChanging(value);
                ReportPropertyChanging("StudentAddress");
                _StudentAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StudentAddress");
                OnStudentAddressChanged();
            }
        }
        private global::System.String _StudentAddress;
        partial void OnStudentAddressChanging(global::System.String value);
        partial void OnStudentAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Telephone
        {
            get
            {
                return _Telephone;
            }
            set
            {
                OnTelephoneChanging(value);
                ReportPropertyChanging("Telephone");
                _Telephone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Telephone");
                OnTelephoneChanged();
            }
        }
        private Nullable<global::System.Decimal> _Telephone;
        partial void OnTelephoneChanging(Nullable<global::System.Decimal> value);
        partial void OnTelephoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CellPhone
        {
            get
            {
                return _CellPhone;
            }
            set
            {
                OnCellPhoneChanging(value);
                ReportPropertyChanging("CellPhone");
                _CellPhone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CellPhone");
                OnCellPhoneChanged();
            }
        }
        private Nullable<global::System.Decimal> _CellPhone;
        partial void OnCellPhoneChanging(Nullable<global::System.Decimal> value);
        partial void OnCellPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StudentRollNumber
        {
            get
            {
                return _StudentRollNumber;
            }
            set
            {
                OnStudentRollNumberChanging(value);
                ReportPropertyChanging("StudentRollNumber");
                _StudentRollNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StudentRollNumber");
                OnStudentRollNumberChanged();
            }
        }
        private global::System.String _StudentRollNumber;
        partial void OnStudentRollNumberChanging(global::System.String value);
        partial void OnStudentRollNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> StudentFee
        {
            get
            {
                return _StudentFee;
            }
            set
            {
                OnStudentFeeChanging(value);
                ReportPropertyChanging("StudentFee");
                _StudentFee = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StudentFee");
                OnStudentFeeChanged();
            }
        }
        private Nullable<global::System.Double> _StudentFee;
        partial void OnStudentFeeChanging(Nullable<global::System.Double> value);
        partial void OnStudentFeeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SchoolBranch
        {
            get
            {
                return _SchoolBranch;
            }
            set
            {
                OnSchoolBranchChanging(value);
                ReportPropertyChanging("SchoolBranch");
                _SchoolBranch = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SchoolBranch");
                OnSchoolBranchChanged();
            }
        }
        private global::System.String _SchoolBranch;
        partial void OnSchoolBranchChanging(global::System.String value);
        partial void OnSchoolBranchChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> familyId
        {
            get
            {
                return _familyId;
            }
            set
            {
                OnfamilyIdChanging(value);
                ReportPropertyChanging("familyId");
                _familyId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("familyId");
                OnfamilyIdChanged();
            }
        }
        private Nullable<global::System.Int32> _familyId;
        partial void OnfamilyIdChanging(Nullable<global::System.Int32> value);
        partial void OnfamilyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StudentStatus
        {
            get
            {
                return _StudentStatus;
            }
            set
            {
                OnStudentStatusChanging(value);
                ReportPropertyChanging("StudentStatus");
                _StudentStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StudentStatus");
                OnStudentStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _StudentStatus;
        partial void OnStudentStatusChanging(Nullable<global::System.Int32> value);
        partial void OnStudentStatusChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schooldbModel", "student_ibfk_1", "classes")]
        public @class @class
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<@class>("schooldbModel.student_ibfk_1", "classes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<@class>("schooldbModel.student_ibfk_1", "classes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<@class> classReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<@class>("schooldbModel.student_ibfk_1", "classes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<@class>("schooldbModel.student_ibfk_1", "classes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schooldbModel", "fees_ibfk_1", "fees")]
        public EntityCollection<fee> fees
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<fee>("schooldbModel.fees_ibfk_1", "fees");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<fee>("schooldbModel.fees_ibfk_1", "fees", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="schooldbModel", Name="teacher")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class teacher : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new teacher object.
        /// </summary>
        /// <param name="teacherId">Initial value of the teacherId property.</param>
        public static teacher Createteacher(global::System.Int32 teacherId)
        {
            teacher teacher = new teacher();
            teacher.teacherId = teacherId;
            return teacher;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 teacherId
        {
            get
            {
                return _teacherId;
            }
            set
            {
                if (_teacherId != value)
                {
                    OnteacherIdChanging(value);
                    ReportPropertyChanging("teacherId");
                    _teacherId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("teacherId");
                    OnteacherIdChanged();
                }
            }
        }
        private global::System.Int32 _teacherId;
        partial void OnteacherIdChanging(global::System.Int32 value);
        partial void OnteacherIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TeacherName
        {
            get
            {
                return _TeacherName;
            }
            set
            {
                OnTeacherNameChanging(value);
                ReportPropertyChanging("TeacherName");
                _TeacherName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TeacherName");
                OnTeacherNameChanged();
            }
        }
        private global::System.String _TeacherName;
        partial void OnTeacherNameChanging(global::System.String value);
        partial void OnTeacherNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TeacherDOB
        {
            get
            {
                return _TeacherDOB;
            }
            set
            {
                OnTeacherDOBChanging(value);
                ReportPropertyChanging("TeacherDOB");
                _TeacherDOB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TeacherDOB");
                OnTeacherDOBChanged();
            }
        }
        private Nullable<global::System.DateTime> _TeacherDOB;
        partial void OnTeacherDOBChanging(Nullable<global::System.DateTime> value);
        partial void OnTeacherDOBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> JoinDate
        {
            get
            {
                return _JoinDate;
            }
            set
            {
                OnJoinDateChanging(value);
                ReportPropertyChanging("JoinDate");
                _JoinDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("JoinDate");
                OnJoinDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _JoinDate;
        partial void OnJoinDateChanging(Nullable<global::System.DateTime> value);
        partial void OnJoinDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TeacherAddress
        {
            get
            {
                return _TeacherAddress;
            }
            set
            {
                OnTeacherAddressChanging(value);
                ReportPropertyChanging("TeacherAddress");
                _TeacherAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TeacherAddress");
                OnTeacherAddressChanged();
            }
        }
        private global::System.String _TeacherAddress;
        partial void OnTeacherAddressChanging(global::System.String value);
        partial void OnTeacherAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Telephone
        {
            get
            {
                return _Telephone;
            }
            set
            {
                OnTelephoneChanging(value);
                ReportPropertyChanging("Telephone");
                _Telephone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Telephone");
                OnTelephoneChanged();
            }
        }
        private Nullable<global::System.Decimal> _Telephone;
        partial void OnTelephoneChanging(Nullable<global::System.Decimal> value);
        partial void OnTelephoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CellPhone
        {
            get
            {
                return _CellPhone;
            }
            set
            {
                OnCellPhoneChanging(value);
                ReportPropertyChanging("CellPhone");
                _CellPhone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CellPhone");
                OnCellPhoneChanged();
            }
        }
        private Nullable<global::System.Decimal> _CellPhone;
        partial void OnCellPhoneChanging(Nullable<global::System.Decimal> value);
        partial void OnCellPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MaritalStatus
        {
            get
            {
                return _MaritalStatus;
            }
            set
            {
                OnMaritalStatusChanging(value);
                ReportPropertyChanging("MaritalStatus");
                _MaritalStatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MaritalStatus");
                OnMaritalStatusChanged();
            }
        }
        private global::System.String _MaritalStatus;
        partial void OnMaritalStatusChanging(global::System.String value);
        partial void OnMaritalStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Designation
        {
            get
            {
                return _Designation;
            }
            set
            {
                OnDesignationChanging(value);
                ReportPropertyChanging("Designation");
                _Designation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Designation");
                OnDesignationChanged();
            }
        }
        private global::System.String _Designation;
        partial void OnDesignationChanging(global::System.String value);
        partial void OnDesignationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> MonthlyTotal
        {
            get
            {
                return _MonthlyTotal;
            }
            set
            {
                OnMonthlyTotalChanging(value);
                ReportPropertyChanging("MonthlyTotal");
                _MonthlyTotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MonthlyTotal");
                OnMonthlyTotalChanged();
            }
        }
        private Nullable<global::System.Double> _MonthlyTotal;
        partial void OnMonthlyTotalChanging(Nullable<global::System.Double> value);
        partial void OnMonthlyTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> BasicSalary
        {
            get
            {
                return _BasicSalary;
            }
            set
            {
                OnBasicSalaryChanging(value);
                ReportPropertyChanging("BasicSalary");
                _BasicSalary = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BasicSalary");
                OnBasicSalaryChanged();
            }
        }
        private Nullable<global::System.Double> _BasicSalary;
        partial void OnBasicSalaryChanging(Nullable<global::System.Double> value);
        partial void OnBasicSalaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Account_Number
        {
            get
            {
                return _Account_Number;
            }
            set
            {
                OnAccount_NumberChanging(value);
                ReportPropertyChanging("Account_Number");
                _Account_Number = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Account_Number");
                OnAccount_NumberChanged();
            }
        }
        private global::System.String _Account_Number;
        partial void OnAccount_NumberChanging(global::System.String value);
        partial void OnAccount_NumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PaymentMode
        {
            get
            {
                return _PaymentMode;
            }
            set
            {
                OnPaymentModeChanging(value);
                ReportPropertyChanging("PaymentMode");
                _PaymentMode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PaymentMode");
                OnPaymentModeChanged();
            }
        }
        private global::System.String _PaymentMode;
        partial void OnPaymentModeChanging(global::System.String value);
        partial void OnPaymentModeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="schooldbModel", Name="timing")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class timing : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new timing object.
        /// </summary>
        /// <param name="timingsId">Initial value of the TimingsId property.</param>
        public static timing Createtiming(global::System.Int32 timingsId)
        {
            timing timing = new timing();
            timing.TimingsId = timingsId;
            return timing;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TimingsId
        {
            get
            {
                return _TimingsId;
            }
            set
            {
                if (_TimingsId != value)
                {
                    OnTimingsIdChanging(value);
                    ReportPropertyChanging("TimingsId");
                    _TimingsId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TimingsId");
                    OnTimingsIdChanged();
                }
            }
        }
        private global::System.Int32 _TimingsId;
        partial void OnTimingsIdChanging(global::System.Int32 value);
        partial void OnTimingsIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> TimeIn
        {
            get
            {
                return _TimeIn;
            }
            set
            {
                OnTimeInChanging(value);
                ReportPropertyChanging("TimeIn");
                _TimeIn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeIn");
                OnTimeInChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _TimeIn;
        partial void OnTimeInChanging(Nullable<global::System.TimeSpan> value);
        partial void OnTimeInChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> TimeOut
        {
            get
            {
                return _TimeOut;
            }
            set
            {
                OnTimeOutChanging(value);
                ReportPropertyChanging("TimeOut");
                _TimeOut = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeOut");
                OnTimeOutChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _TimeOut;
        partial void OnTimeOutChanging(Nullable<global::System.TimeSpan> value);
        partial void OnTimeOutChanged();

        #endregion
    
    }

    #endregion
    
}
